version: '3.8'

services:
  mysql-productos:
    image: mysql:8.0
    container_name: mysql-productos
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ms-productsdb
      MYSQL_USER: productos_user
      MYSQL_PASSWORD: productos_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: