spring:
  datasource:
    url: jdbc:mysql://localhost:3307/productos_local
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          # ? Crea/actualiza tablas automáticamente
    show-sql: true              # ? Muestra SQL en consola
    properties:
      hibernate:
        format_sql: true        # ? SQL formateado bonito

logging:
  level:
    com.empresa.proyecto: DEBUG  # ? Logs detallados
    org.hibernate.SQL: DEBUG